FROM rockylinux/rockylinux:9

RUN dnf install -y sudo git

RUN dnf install -y apr-devel bison bzip2-devel cmake3 diffutils flex gcc gcc-c++ glibc-langpack-en glibc-locale-source iproute krb5-devel libcurl-devel libevent-devel libxml2-devel libuuid-devel libzstd-devel lz4-devel net-tools openldap-devel openssl-devel openssh-server pam-devel perl perl-ExtUtils-Embed perl-Test-Simple perl-Env python3-devel python3-pip readline-devel rsync wget which zlib-devel

RUN dnf install -y --enablerepo=crb libuv-devel libyaml-devel perl-IPC-Run protobuf-devel

RUN useradd -U -m -s /bin/bash gpadmin

RUN echo 'gpadmin ALL=(ALL) NOPASSWD:ALL' | tee /etc/sudoers.d/90-gpadmin

RUN echo "compile and install xerces-c" && \ 
  XERCES_LATEST_RELEASE=3.3.0 && \
  XERCES_INSTALL_PREFIX="/usr/local/xerces-c" && \
  wget -nv "https://dlcdn.apache.org//xerces/c/3/sources/xerces-c-${XERCES_LATEST_RELEASE}.tar.gz" && \
  echo "$(curl -sL https://dlcdn.apache.org//xerces/c/3/sources/xerces-c-${XERCES_LATEST_RELEASE}.tar.gz.sha256)" | sha256sum -c - && \
  tar xf "xerces-c-${XERCES_LATEST_RELEASE}.tar.gz" && \
  rm "xerces-c-${XERCES_LATEST_RELEASE}.tar.gz" && \
  cd xerces-c-${XERCES_LATEST_RELEASE} && \
  ./configure --prefix="${XERCES_INSTALL_PREFIX}-${XERCES_LATEST_RELEASE}" && \
  make -j$(nproc) && \
  make check && \
  make install && \
  ln -s ${XERCES_INSTALL_PREFIX}-${XERCES_LATEST_RELEASE} ${XERCES_INSTALL_PREFIX}

USER gpadmin
RUN echo "Download Source Code (2.x branch)" && \
  git clone https://github.com/apache/cloudberry.git ~/cloudberry && \
  cd ~/cloudberry && \
  git fetch --tags && \
  git checkout tags/2.0.0-incubating && \
  git submodule update --init --recursive

RUN echo "Prepare the build environment for Apache Cloudberry" && \
  sudo rm -rf /usr/local/cloudberry-db && \
  sudo chmod a+w /usr/local && \
  mkdir -p /usr/local/cloudberry-db/lib && \
  sudo cp -v /usr/local/xerces-c/lib/libxerces-c.so /usr/local/xerces-c/lib/libxerces-c-3.*.so /usr/local/cloudberry-db/lib && \
  sudo chown -R gpadmin:gpadmin /usr/local/cloudberry-db

RUN echo "Run configure" && \
  cd ~/cloudberry && \
  export LD_LIBRARY_PATH=/usr/local/cloudberry-db/lib:LD_LIBRARY_PATH && \
  ./configure --prefix=/usr/local/cloudberry-db \
            --disable-external-fts \
            --enable-debug \
            --enable-cassert \
            --enable-debug-extensions \
            --enable-gpcloud \
            --enable-ic-proxy \
            --enable-mapreduce \
            --enable-orafce \
            --enable-orca \
            --enable-pax \
            --enable-pxf \
            --enable-tap-tests \
            --with-gssapi \
            --with-ldap \
            --with-libxml \
            --with-lz4 \
            --with-pam \
            --with-perl \
            --with-pgport=5432 \
            --with-python \
            --with-pythonsrc-ext \
            --with-ssl=openssl \
            --with-uuid=e2fs \
            --with-includes=/usr/local/xerces-c/include \
            --with-libraries=/usr/local/cloudberry-db/lib

RUN echo "Build and install Cloudberry and its contrib modules" && \
  make -j$(nproc) -C ~/cloudberry && \
  make -j$(nproc) -C ~/cloudberry/contrib && \
  make install -C ~/cloudberry && \
  make install -C ~/cloudberry/contrib



